### ISSUE TITLE
Idea dump

### ISSUE THREAD

**Issue by Stanzilla** [nebularg/oRA3#1]
- [ ] Show placeholder icons when you can't check the player (out of range etc)
- [x] Tooltips? I mean it's obvious which icon is which etc but yeah, can also explain the color coding.
- [ ] Always show food/flask/rune icon during the ready check with color coding?
- [x] Option to disable rune checking
- [x] Option to allow/disallow lesser food/flasks
- [ ] ^ Should be on by default, was off for me.
- [ ] http://www.wowace.com/addons/big-wigs/tickets/715-item-level-check-pre-pull/ ? Item Level check might come in handy, people still might have a fishing hat, teleport ring etc.
- [ ] ^ Could be an option for the `Gear` check we already have, with an option in `Ready Check` to print or alert about it

I can see people being confused by the options as I was at first, too. Maybe we could rename `Consumables` to `Checks` and have `Consumables` as entry in there.

**Comment by Stanzilla** [comment]
- [ ] Disable all of it in LFR?

**Comment by Stanzilla** [comment]
- [ ] Disable being able to right click the unlocked ring/cooldown trackers to open the config in combat

**Comment by nebularg** [comment]
if you don't want to interact with it, lock it. wtf kind of feature request is that

**Comment by Stanzilla** [comment]
Ok I tested the new build and thought about the way we display the icons. So my previous suggestion was to always display the three icons so it looks a little more consistent but that also added a lot of visual clutter. So I actually think hiding everything that passes the test is ok BUT we need to reorder the icons to avoid the "punchcard-look". So we need to align the icons to the right side of the grid and expand to the left.

Previous:

_XX
__X
XXX
X__
XX_
___
XX_
X_X

Suggestion:

_XX
__X
XXX
__X
_XX
_XX
_XX

**Comment by nebularg** [comment]
1) the "punch card" look was a design choice, the buffs are in a grid and don't move on purpose.
2) eating will get spoon/fork icon, i just hadn't got back to that yet. probably going to map relevant eating buffs to their well fed counterpart for the tooltip or such

**Comment by Stanzilla** [comment]
Ready check still showed flask/food etc icons in LFR today
